from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    BigInteger,
    ForeignKey,
    Identity,
    TIMESTAMP,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# These models mirror the applied Alembic schema by hand — the
# migration is the source of truth for the physical schema (env.py keeps
# target_metadata = None, so nothing here is autogenerated or diffed).


class Base(DeclarativeBase):
    pass


class Session(Base):
    __tablename__ = "sessions"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_text: Mapped[str] = mapped_column(Text, nullable=False)
    additional_details: Mapped[str | None] = mapped_column(Text, nullable=True)
    # FK to diagram_versions.id is added by a deferred ALTER in 0001 (the two
    # tables reference each other). ondelete="SET NULL" there; the app always
    # sets head explicitly inside the same transaction as the version insert.
    head_version_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    # Task 06 concern (lease/lock) — modelled only so the ORM class matches
    # the table; no behaviour hangs off these in Task 05.
    locked_until: Mapped[datetime | None] = mapped_column(nullable=True)
    lock_token: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=func.now()
    )


class DiagramVersion(Base):
    __tablename__ = "diagram_versions"

    id: Mapped[int] = mapped_column(BigInteger, Identity(), primary_key=True)
    # Separate DB-generated monotonic counter — ordering key for history and
    # for "previous version" lookups. Distinct from `id` on purpose (see the
    # id-vs-seq split from Task 04). Never set by the app.
    seq: Mapped[int] = mapped_column(
        BigInteger, Identity(), nullable=False, unique=True
    )
    session_id: Mapped[str] = mapped_column(
        Text, ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False
    )
    mermaid_code: Mapped[str] = mapped_column(Text, nullable=False)
    parent_version_id: Mapped[int | None] = mapped_column(
        BigInteger,
        ForeignKey("diagram_versions.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=func.now()
    )


class Message(Base):
    __tablename__ = "messages"

    id: Mapped[int] = mapped_column(BigInteger, Identity(), primary_key=True)
    seq: Mapped[int] = mapped_column(
        BigInteger, Identity(), nullable=False, unique=True
    )
    session_id: Mapped[str] = mapped_column(
        Text, ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False
    )
    role: Mapped[str] = mapped_column(Text, nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=func.now()
    )


class Turn(Base):
    __tablename__ = "turns"
    __table_args__ = (
        UniqueConstraint(
            "session_id",
            "request_id",
            name="uq_turns_session_id_request_id",
        ),
    )

    id: Mapped[int] = mapped_column(BigInteger, Identity(), primary_key=True)
    session_id: Mapped[str] = mapped_column(
        Text, ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False
    )
    request_id: Mapped[str] = mapped_column(Text, nullable=False)
    request_hash: Mapped[str] = mapped_column(Text, nullable=False)
    response_json: Mapped[dict[str, object] | None] = mapped_column(
        JSONB(none_as_null=True), nullable=True
    )
    claimed_until: Mapped[datetime | None] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True
    )
    claim_token: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
